"""remove legacy gpu domain files; drop users.gpu_lvl

Revision ID: 7c6142541c8f
Revises: 3b60ffaae9e6
Create Date: 2025-12-15 18:43:46.554613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6142541c8f'
down_revision: Union[str, None] = '3b60ffaae9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gpu_lvl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gpu_lvl', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
